# General settings
"frequency": 700  # in MHz
"fit_method": "amgo"  # leastsq or amgo or anything scipy supports
"data_path": "/Users/florianwolf/Downloads/sig_andrea.txt"

# reference sigma settings
"sigA": "lowest_T"  # lowest_T, or custom for usage of sigA values in sigA column (not tested), // fit, or numeric value to be coded
"sigB": "0"  # 0, highest_T or fit or custom for usage of values from file
"correct_for_correlation_time": false  # recommended: True corrects sigma for T-dependent global correlation time

# Fitting equation settings
"max_iterations": 1000
"Cp_model": True  # True/False, False results in the use of the van't Hoff equation
"fit_SM": False  # True or False
"Tm": 300  # optional, is just used as an initial guess for Tm in the fit, numeric value in K or None (sets value to 1)
"fix_Tm": false  # if True, Tm won't be fit (to be used with setting Tm above)

# test_features (will be removed in the future)
"ignore_lowest_T": true  # ignores lowest temperature in plotting and fitting, use with "lowest_T"